const Map<String, String> categories = {
  'Top headlines': 'google-news-in',
  'Business': 'business',
  'Business Insider': 'business-insider',
  'Entertainment': 'entertainment',
  'Buzzfeed': 'buzzfeed',
  'MTV': 'mtv-news',
  'Health': 'health',
  'Medical News Today': 'medical-news-today',
  'Science': 'science',
  'New Scientist': 'new-scientist',
  'Sports': 'sports',
  'ESPN': 'espn',
  'Technology': 'technology',
  'Ars Technica': 'ars-technica',
  'Wired': 'wired',
  'IGN': 'ign',
  'Polygon': 'polygon',
  'World News': 'google-news',
  'Al Jazeera': 'al-jazeera-english',
  'BBC News': 'bbc-news',
  'CNN': 'cnn',
  'Independent': 'independent'
};
